//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emblem_Order_Information
    {
        public int Customer_ID { get; set; }
        public string Contact_Name { get; set; }
        public string Company { get; set; }
        public string Address1 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Fax_other_phone { get; set; }
        public string Customer_code { get; set; }
        public string Terms_Code { get; set; }
        public string PO_Number { get; set; }
        public string Oder_Date { get; set; }
        public string Request_Date { get; set; }
        public bool Rush_Order_Yes { get; set; }
        public bool Rush_Order_No { get; set; }
        public bool Ship_Via_Red { get; set; }
        public bool Ship_Via_Blue { get; set; }
        public bool Ship_Via_Orange { get; set; }
        public bool Ship_Via_Ground { get; set; }
        public bool Ship_Via_Other { get; set; }
        public bool Pre_pro_sample_yes { get; set; }
        public bool pre_pro_sample_no { get; set; }
        public string Pre_pro_sample_other { get; set; }
        public string Quantity { get; set; }
        public string Emblem_Name { get; set; }
        public bool First_Order_Yes { get; set; }
        public bool First_Order_No { get; set; }
        public string Reorder_BR_PO { get; set; }
        public Nullable<System.DateTime> Date_of_Old_order { get; set; }
        public string Length { get; set; }
        public string Width { get; set; }
        public string Actual_size { get; set; }
        public bool Shape_circle { get; set; }
        public bool Shape_square { get; set; }
        public bool Shape_rect { get; set; }
        public bool Shape_Other { get; set; }
        public Nullable<double> Percent_of_emblem { get; set; }
        public Nullable<double> Price_Each { get; set; }
        public Nullable<double> Deposit { get; set; }
        public string Border { get; set; }
        public bool merrow { get; set; }
        public bool hand_cut { get; set; }
        public bool other { get; set; }
        public string border_other_text { get; set; }
        public bool backing_plain { get; set; }
        public bool backing_heatseal { get; set; }
        public bool backing_plastic { get; set; }
        public bool backing_other { get; set; }
        public string backing_other_text { get; set; }
        public bool special_thread_neon { get; set; }
        public bool special_thread_metallic { get; set; }
        public string special_thread_other { get; set; }
        public string total_colors { get; set; }
        public string color1 { get; set; }
        public string color2 { get; set; }
        public string color3 { get; set; }
        public string color4 { get; set; }
        public string color5 { get; set; }
        public string color6 { get; set; }
        public string color7 { get; set; }
        public string color8 { get; set; }
        public string color9 { get; set; }
        public string color10 { get; set; }
        public string color11 { get; set; }
        public string color12 { get; set; }
        public string special_instructions { get; set; }
        public string Ship_via_other_text { get; set; }
        public string Background { get; set; }
        public bool Duplicate_Sample { get; set; }
        public bool As_Sample { get; set; }
        public bool Reorder_Exactly { get; set; }
        public bool Reorder_Change { get; set; }
    }
}
