//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAH
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNPI_Emblem_Order
    {
        public string BR_Number { get; set; }
        public string Customer_Code { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<System.DateTime> Request_Date { get; set; }
        public Nullable<System.DateTime> Cust_Request_Date { get; set; }
        public Nullable<System.DateTime> TW_Confirm_Date { get; set; }
        public Nullable<System.DateTime> Ship_Date { get; set; }
        public string PO_Number { get; set; }
        public string Ordered_By { get; set; }
        public bool First_Order_ { get; set; }
        public string Reorder_BR__ { get; set; }
        public string Sample { get; set; }
        public string Name { get; set; }
        public Nullable<float> Length { get; set; }
        public Nullable<float> Width { get; set; }
        public Nullable<float> Size { get; set; }
        public string Size_Info { get; set; }
        public Nullable<float> C__of_Emblem { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Price_Per_Unit { get; set; }
        public string Price_List { get; set; }
        public Nullable<float> Price_List__ { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> Sample_Charge { get; set; }
        public Nullable<decimal> Rush_Order_ { get; set; }
        public Nullable<decimal> Order_Total { get; set; }
        public bool Special_Price_ { get; set; }
        public Nullable<decimal> Special_Amount { get; set; }
        public bool Drop_Ship_ { get; set; }
        public string Drop_Name { get; set; }
        public string Drop_Company { get; set; }
        public string Drop_Address { get; set; }
        public string Drop_City { get; set; }
        public string Drop_State { get; set; }
        public string Drop_Zip { get; set; }
        public bool Deposit_Required_ { get; set; }
        public bool Deposit_Confirmed_ { get; set; }
        public bool Order_Confirmed_ { get; set; }
        public string Background { get; set; }
        public string Background_Type { get; set; }
        public Nullable<float> Background_Price__ { get; set; }
        public string Border { get; set; }
        public string Border_Type { get; set; }
        public Nullable<decimal> Border_Price { get; set; }
        public string Backing { get; set; }
        public Nullable<decimal> Backing_Price { get; set; }
        public string Special_Thread { get; set; }
        public Nullable<float> Special_Thread_Price__ { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string Total_Colors { get; set; }
        public string C1_Color_Break { get; set; }
        public string C2_Color_Break { get; set; }
        public string C3_Color_Break { get; set; }
        public string C4_Color_Break { get; set; }
        public string C5_Color_Break { get; set; }
        public string C6_Color_Break { get; set; }
        public string C7_Color_Break { get; set; }
        public string C8_Color_Break { get; set; }
        public string C9_Color_Break { get; set; }
        public string C10_Color_Break { get; set; }
        public string C11_Color_Break { get; set; }
        public string C12_Color_Break { get; set; }
        public string Art_Design { get; set; }
        public string Customer_Notes { get; set; }
        public string Rep { get; set; }
        public bool RushOrder { get; set; }
        public Nullable<float> RushOrderPercent { get; set; }
        public string ShipVia { get; set; }
        public string Shape { get; set; }
        public bool Duplicate { get; set; }
        public bool ReorderExactly { get; set; }
        public bool AsSample { get; set; }
        public bool ReorderChange { get; set; }
        public bool TungLi { get; set; }
        public bool FineThread { get; set; }
        public bool Event { get; set; }
        public string ShipCompany { get; set; }
        public string ShipAddress { get; set; }
        public string ShipCity { get; set; }
        public string ShipState { get; set; }
        public string ShipZip { get; set; }
        public bool RushOrd { get; set; }
    }
}
